name: Publicar cliente
on:
  push:
    branches:
      - master

jobs:
  publicar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm ci
          npm run build
          echo $VITE_API_URL
          echo "hola"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
