name: Publicar cliente
on:
  push:
    branches:
      - master

env:
  VITE_API_URL: ${{ vars.VITE_API_URL }}

jobs:
  publicar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm ci
          npm run build
          cp dist/index.html dist/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
